### ISSUE TITLE
Some Google voices don't work (Journey and Studio)

### ISSUE THREAD

**Issue by superluig164** [ken107/read-aloud#427]
When trying to use Google's Journey or Studio voices, I get this error:
![image](https://github.com/user-attachments/assets/9be71602-225f-4e20-9558-b4ccdd432bf5)
A couple of months back, I experienced some issues with Journey voices in some other software, due to Google changing the way they accept API requests for Journey voices.  They never supported pitch and speed adjustments, but now, the API call must not include those parameters at all, or else it will return an error.  Additionally, Journey voices must be requested in WAV format, MP3 and OGG do not work.  I'm not sure if this is the same reason why they don't work in Read Aloud, but it might help.  I do have my GCP API key entered in settings.

**Comment by superluig164** [comment]
Bumping this, as it's still an issue.  These voices work flawlessly using https://github.com/pgmichael/wavenet-for-chrome, however I use Firefox now, so that extension is out of reach.  Hopefully this can be resolved in Read Aloud on both platforms.

**Comment by ken107** [comment]
Fixed in version 2.19 by 0b03da0723f44303c4694b155fd798d3537c912b

Google Journey voices have been renamed to [Chirp-HD](https://cloud.google.com/text-to-speech/docs/voice-types#chirp_hd_voices)

**Comment by superluig164** [comment]
Sorry to bump this - is there any way I can get this update early on Firefox?  Seems like I'm stuck on 1.77 and there aren't any updates available.  If not, is there a timeline for the rollout on Firefox?  

Thank you

**Comment by ken107** [comment]
No problem, i submitted version 1.78 pending approval, which can take a week or more. It has fix to support Studio and Journey (which has been renamed Chirp-HD) voices.

**Comment by superluig164** [comment]
Thank you!  I'll keep an eye out for it

**Comment by superluig164** [comment]
I've got version 1.78 now, and unfortunately it seems like things are still not working with Google's voices.  I do have my API key added to the settings menu.  The original Chirp voices do have a different error now, though.

It may be worth exploring the source code of [Wavenet For Chrome](https://github.com/pgmichael/wavenet-for-chrome).  While I'm not a programmer, I use these Google voices everywhere, and so far that has been the absolute best implementation of them.  

![Image](https://github.com/user-attachments/assets/0d947552-38e2-417a-aaf6-045cb2451187)

![Image](https://github.com/user-attachments/assets/229afcab-380e-4532-8e8b-3838a10526ff)

**Comment by superluig164** [comment]
OK, I'll watch out for the next version.  Thanks.

**Comment by ken107** [comment]
We can't do anything about hallucination or hallucinated pauses as they're Google's problems.

We're already [segmenting the text](https://github.com/ken107/read-aloud/blob/3f17a7aaa4ea35097e746b7036c9942ef4acd43c/js/speech.js#L57) at sentence+paragraph boundaries every ~750 characters.

Can you find documentation for the ideal query size for Chirp voices?  We can't make trial-and-error types of changes.

**Comment by superluig164** [comment]
Obviously I know you can't directly address long pauses and hallucinations, but I'm telling you from testing that it happens far less with shorter queries.  Please test it yourself instead of blowing me off, you can either try it using the API directly or using Wavenet for Chrome's implementation (which I've referenced multiple times).  It's a very clear difference that you can tell just by running both extensions side by side and reading the same long passage (especially those with lots of new lines like lists or charts.)

This isn't trial and error, this is a real issue which I'm attempting to help bring to light so thar Read Aloud can work better for _everyone,_ not just for myself.  If I wanted it just for myself I would have already built my own version and not said a word.

Thank you for your consideration.
